name: Publish Application on GitHub Pages
on:
  push:
    branches:
      - main
      
jobs:
  # Build job
  build:
    name: Build Kotlin/Wasm
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create local.properties
      env:
        PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
        PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
        GH_PAT: ${{ secrets.GH_PAT }} 
      run: echo -e 'PUBLIC_API_KEY=${{ secrets.PUBLIC_API_KEY }}\nPRIVATE_API_KEY=${{ secrets.PRIVATE_API_KEY }}\nGH_PAT=${{ secrets.GH_PAT }}' > ./local.properties
    - name: Run Gradle Tasks
      run: ./gradlew clean wasmJsBrowserDistribution

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: composeApp/build/dist/wasmJs/productionExecutable
    environment: secrets

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
